AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chatbot Lambda con FastAPI y OpenAI API

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 512
    Environment:
      Variables:
        OPENAI_API_KEY: !Ref OpenAIApiKey

Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chatbot-lambda
      Handler: chatbot.lambda.lambda_handler
      CodeUri: build/chatbot-lambda.zip
      Events:
        ChatbotApi:
          Type: Api
          Properties:
            Path: /chat
            Method: post
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: get
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - sns:Publish
              - sqs:SendMessage
            Resource: "*"

Parameters:
  OpenAIApiKey:
    Type: String
    Description: "Clave API de OpenAI"

Outputs:
  ChatbotApiUrl:
    Description: "URL del endpoint de Chatbot"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chat"
